# <auto-generated>
# Source: winsmux-app/src/modelCapabilities.ts commonContractPackage
# Generated by winsmux-app/scripts/generate-common-contract-bindings.mjs.
# Do not edit by hand.

$script:BridgeCommonContractPackageVersion = '0.36.26'
$script:BridgeCommonContractVocabularies = @{
    runtimeProviderIds = @('provider-default', 'codex', 'claude', 'antigravity', 'grok-build', 'openrouter')
    modelSources = @('provider-default', 'cli-discovery', 'provider-api', 'official-doc', 'operator-override')
    reasoningEfforts = @('provider-default', 'low', 'medium', 'high', 'max', 'xhigh')
    backendCapabilities = @('any', 'agent-cli', 'antigravity', 'api_llm', 'colab_cli')
    promptTransports = @('argv', 'file', 'stdin')
    modelReadiness = @('selectable', 'candidate', 'setup-required', 'runnable', 'blocked', 'reference-only', 'unavailable')
    runtimeWorkerReadiness = @('runnable', 'setup-required', 'blocked')
    workerPaneReadiness = @('ready', 'blocked', 'pending')
    agentVaultCommandProviders = @('claude', 'codex', 'opencode')
    benchmarkFamilies = @('agent-arena', 'code-arena', 'winsmux-local')
}

function Get-BridgeCommonContractVocabularyValues {
    param([Parameter(Mandatory = $true)][string]$Name)

    if (-not $script:BridgeCommonContractVocabularies.ContainsKey($Name)) {
        throw "Unknown common contract vocabulary '$Name'."
    }

    return @($script:BridgeCommonContractVocabularies[$Name])
}

function Test-BridgeCommonContractVocabularyValue {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [AllowNull()][string]$Value
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $false
    }

    $normalized = $Value.Trim().ToLowerInvariant()
    return ($normalized -in @(Get-BridgeCommonContractVocabularyValues -Name $Name))
}

function Get-BridgeCommonContractSupportedValuesText {
    param([Parameter(Mandatory = $true)][string]$Name)

    return ((Get-BridgeCommonContractVocabularyValues -Name $Name) -join ', ')
}
