# <auto-generated>
# Source: docs/control-plane-contract.v1.json
# Generated by winsmux-app/scripts/generate-control-plane-bindings.mjs.
# Do not edit by hand.

CONTROL_PLANE_CONTRACT_VERSION = 1

CONTROL_PIPE_METHODS = (
    "desktop.control_plane.contract",
    "desktop.summary.snapshot",
    "desktop.run.explain",
    "desktop.run.compare",
    "desktop.run.promote",
    "desktop.run.pick_winner",
    "desktop.voice.capture_status",
    "pty.spawn",
    "pty.write",
    "pty.resize",
    "pty.capture",
    "pty.respawn",
    "pty.close",
    "desktop.operator.snapshot",
    "desktop.operator.submit",
    "desktop.pairing.confirm",
)

DESKTOP_METHODS = (
    "desktop.control_plane.contract",
    "desktop.summary.snapshot",
    "desktop.run.explain",
    "desktop.run.compare",
    "desktop.run.promote",
    "desktop.run.pick_winner",
    "desktop.voice.capture_status",
)

PTY_METHODS = (
    "pty.spawn",
    "pty.write",
    "pty.resize",
    "pty.capture",
    "pty.respawn",
    "pty.close",
)

OPERATOR_METHODS = (
    "desktop.operator.snapshot",
    "desktop.operator.submit",
)

PAIRING_METHODS = (
    "desktop.pairing.confirm",
)

INTERNAL_DESKTOP_METHODS_EXCLUDED = (
    "desktop.workers.status",
    "desktop.workers.start",
    "desktop.runtime.roles.apply",
    "desktop.dogfood.event",
    "desktop.explorer.list",
    "desktop.editor.read",
)
