#!/usr/bin/env node
// policy-drift.js — Detect drift between permissions-spec.json deny rules and OpenShell policy YAML
// Part of Shield Harness: ensures policy files stay in sync with the canonical deny rules
"use strict";

const fs = require("fs");
const path = require("path");

// --- Dependencies (local modules) ---

const { loadPermissionsSpec } = require("./permissions-validator");
const { classifyRulesByDomain } = require("./tier-policy-gen");

// --- YAML Parsing (regex-based, no js-yaml dependency) ---

/**
 * Extract a YAML list section by name.
 * Expects predictable structure generated by tier-policy-gen.js:
 *   section_name:
 *     - item1
 *     - item2
 *
 * @param {string} content - Full YAML file content
 * @param {string} sectionName - Name of the section (e.g., "deny_read")
 * @returns {string[]} List of items found under the section
 */
function extractYamlList(content, sectionName) {
  // Match section header followed by indented list items
  var pattern = new RegExp(
    sectionName + ":\\n((?:[ \\t]+-[ \\t]+.+\\n)*)",
    "m",
  );
  var match = content.match(pattern);
  if (!match) return [];
  return match[1]
    .split("\n")
    .filter(function (l) {
      return l.trim().startsWith("- ");
    })
    .map(function (l) {
      return l.trim().replace(/^-\s+/, "");
    });
}

/**
 * Extract blocked network operations from YAML comment block.
 * Expects format generated by tier-policy-gen.js:
 *   # Blocked network operations (from permissions-spec.json deny rules):
 *   #   - curl *
 *   #   - wget *
 *
 * @param {string} content - Full YAML file content
 * @returns {string[]} List of blocked network commands
 */
function extractBlockedNetworkComments(content) {
  var pattern =
    /# Blocked network operations[^\n]*:\n((?:#[ \t]+-[ \t]+.+\n)*)/m;
  var match = content.match(pattern);
  if (!match) return [];
  return match[1]
    .split("\n")
    .filter(function (l) {
      return l.trim().startsWith("#");
    })
    .map(function (l) {
      return l.trim().replace(/^#\s+-\s+/, "");
    });
}

/**
 * Parse all relevant sections from a policy YAML file.
 * Returns structured data without requiring js-yaml.
 *
 * @param {string} content - Full YAML file content
 * @returns {{
 *   denyRead: string[],
 *   denyWrite: string[],
 *   readWrite: string[],
 *   blockedNetwork: string[]
 * }}
 */
function parsePolicyYaml(content) {
  return {
    denyRead: extractYamlList(content, "deny_read"),
    denyWrite: extractYamlList(content, "deny_write"),
    readWrite: extractYamlList(content, "read_write"),
    blockedNetwork: extractBlockedNetworkComments(content),
  };
}

// --- Drift Detection ---

/**
 * Check drift between permissions-spec deny rules and OpenShell policy YAML.
 *
 * Compares the classified deny rules from permissions-spec.json against
 * the content of policy YAML files in the specified directory.
 *
 * Drift rules:
 *   1. Missing filesystem deny (read): spec denyRead paths not in policy deny_read
 *   2. Missing filesystem deny (write): spec denyWrite paths not in policy deny_write
 *   3. Policy allows denied: paths in denyRead/denyWrite that also appear in read_write
 *   4. Missing network deny: network commands not in blocked network comments
 *   5. No policy files: skip (no drift reported)
 *   6. No spec file: skip (no drift reported)
 *   7. Parse errors: fail-safe (no drift, warning logged)
 *
 * @param {{ specPath: string, policyDir: string }} params
 * @returns {{
 *   has_drift: boolean,
 *   warnings: string[],
 *   details: {
 *     missing_filesystem_deny: string[],
 *     missing_network_deny: string[],
 *     policy_allows_denied: string[]
 *   },
 *   checked_at: string
 * }}
 */
function checkPolicyDrift({ specPath, policyDir }) {
  var emptyResult = {
    has_drift: false,
    warnings: [],
    details: {
      missing_filesystem_deny: [],
      missing_network_deny: [],
      policy_allows_denied: [],
    },
    checked_at: new Date().toISOString(),
  };

  // Rule 6: No spec file — skip silently
  if (!specPath || !fs.existsSync(specPath)) {
    return emptyResult;
  }

  // Rule 5: No policy directory or no .yaml files — skip silently
  if (!policyDir || !fs.existsSync(policyDir)) {
    return emptyResult;
  }

  var policyFiles;
  try {
    policyFiles = fs.readdirSync(policyDir).filter(function (f) {
      return f.endsWith(".yaml") || f.endsWith(".yml");
    });
  } catch (e) {
    return emptyResult;
  }

  if (policyFiles.length === 0) {
    return emptyResult;
  }

  // Load and classify spec deny rules
  var spec;
  try {
    spec = loadPermissionsSpec(specPath);
  } catch (err) {
    return {
      has_drift: false,
      warnings: ["parse_error: spec load failed \u2014 " + err.message],
      details: {
        missing_filesystem_deny: [],
        missing_network_deny: [],
        policy_allows_denied: [],
      },
      checked_at: new Date().toISOString(),
    };
  }

  var classified;
  try {
    classified = classifyRulesByDomain(spec.deny);
  } catch (err) {
    return {
      has_drift: false,
      warnings: [
        "parse_error: rule classification failed \u2014 " + err.message,
      ],
      details: {
        missing_filesystem_deny: [],
        missing_network_deny: [],
        policy_allows_denied: [],
      },
      checked_at: new Date().toISOString(),
    };
  }

  // Aggregate policy content from all YAML files
  var aggregated = {
    denyRead: new Set(),
    denyWrite: new Set(),
    readWrite: new Set(),
    blockedNetwork: new Set(),
  };

  for (var i = 0; i < policyFiles.length; i++) {
    var filePath = path.join(policyDir, policyFiles[i]);
    var content;
    try {
      content = fs.readFileSync(filePath, "utf8");
    } catch (err) {
      // Rule 7: Parse error — fail-safe
      return {
        has_drift: false,
        warnings: [
          "parse_error: cannot read " + filePath + " \u2014 " + err.message,
        ],
        details: {
          missing_filesystem_deny: [],
          missing_network_deny: [],
          policy_allows_denied: [],
        },
        checked_at: new Date().toISOString(),
      };
    }

    var parsed;
    try {
      parsed = parsePolicyYaml(content);
    } catch (err) {
      return {
        has_drift: false,
        warnings: [
          "parse_error: cannot parse " + filePath + " \u2014 " + err.message,
        ],
        details: {
          missing_filesystem_deny: [],
          missing_network_deny: [],
          policy_allows_denied: [],
        },
        checked_at: new Date().toISOString(),
      };
    }

    parsed.denyRead.forEach(function (p) {
      aggregated.denyRead.add(p);
    });
    parsed.denyWrite.forEach(function (p) {
      aggregated.denyWrite.add(p);
    });
    parsed.readWrite.forEach(function (p) {
      aggregated.readWrite.add(p);
    });
    parsed.blockedNetwork.forEach(function (cmd) {
      aggregated.blockedNetwork.add(cmd);
    });
  }

  // --- Compare classified rules against aggregated policy ---

  var warnings = [];
  var missingFilesystemDeny = [];
  var missingNetworkDeny = [];
  var policyAllowsDenied = [];

  // Rule 1: Missing filesystem deny (read)
  for (var ri = 0; ri < classified.denyRead.length; ri++) {
    var readPath = classified.denyRead[ri];
    if (!aggregated.denyRead.has(readPath)) {
      warnings.push("deny_read missing in policy: " + readPath);
      missingFilesystemDeny.push(readPath);
    }
  }

  // Rule 2: Missing filesystem deny (write)
  for (var wi = 0; wi < classified.denyWrite.length; wi++) {
    var writePath = classified.denyWrite[wi];
    if (!aggregated.denyWrite.has(writePath)) {
      warnings.push("deny_write missing in policy: " + writePath);
      missingFilesystemDeny.push(writePath);
    }
  }

  // Rule 3: Policy allows denied — conflict detection
  var allDeniedPaths = new Set(
    classified.denyRead.concat(classified.denyWrite),
  );
  aggregated.readWrite.forEach(function (rwPath) {
    if (allDeniedPaths.has(rwPath)) {
      warnings.push("conflict: read_write allows denied path: " + rwPath);
      policyAllowsDenied.push(rwPath);
    }
  });

  // Rule 4: Missing network deny
  for (var ni = 0; ni < classified.network.length; ni++) {
    var netCmd = classified.network[ni];
    if (!aggregated.blockedNetwork.has(netCmd)) {
      warnings.push(
        "blocked network command missing in policy comments: " + netCmd,
      );
      missingNetworkDeny.push(netCmd);
    }
  }

  var hasDrift =
    missingFilesystemDeny.length > 0 ||
    missingNetworkDeny.length > 0 ||
    policyAllowsDenied.length > 0;

  return {
    has_drift: hasDrift,
    warnings: warnings,
    details: {
      missing_filesystem_deny: missingFilesystemDeny,
      missing_network_deny: missingNetworkDeny,
      policy_allows_denied: policyAllowsDenied,
    },
    checked_at: new Date().toISOString(),
  };
}

module.exports = {
  // Main entry point
  checkPolicyDrift: checkPolicyDrift,
  // Parsing helpers (exported for unit testing)
  extractYamlList: extractYamlList,
  extractBlockedNetworkComments: extractBlockedNetworkComments,
  parsePolicyYaml: parsePolicyYaml,
};
